name: ViaOps CI
on:
  push:
  workflow_dispatch:

env:
  NAMESPACE_PREFIX: "adlm-dummy"
  PROJECT_NAME: "reference-blank"
  APPLICATION_NAMES: "reference-blank"
  SQUAD_NAME: "ADLM DevOps"
  SERVICE_NOW_CI: "SYS-ID"
  DEPLOYMENT_STRATEGY: "aks"
  HARBOR_PROJECT_NAME: "adlm-dummy"
  SOURCE_REGISTRY: "harbor01.viavarejo.com.br"

jobs:
  pipeline:
    runs-on: self-hosted
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Checkout Convair Actions
      uses: actions/checkout@v2
      with:
        repository: viavarejo-internal/convair-actions
        token: ${{ secrets.ACTIONS_TOKEN }}
        path: ./.convair-actions
        ref: main
    - name: Define Branch Type
      uses: ./.convair-actions/define-type

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleQa --warning-mode all
      env:
        JAVA_OPTS: "--add-opens java.base/java.io=ALL-UNNAMED"
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-posse-qa.apk
        path: app/build/outputs/apk/qa/app-posse-qa.apk
