name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle files
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up Node.js 20 (again for gradle-build-action)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Clean project
        run: ./gradlew clean

      - name: Build with Gradle
        run: ./gradlew assembleRelease --profile

      - name: Set up Node.js 20 (again for artifact upload)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Sign and Verify APK
        run: |
          echo ${{ secrets.KEYSTORE_BASE64 }} | base64 --decode > keystore/santander.jks
          ${ANDROID_HOME}/build-tools/33.0.0/apksigner sign --ks keystore/santander.jks --ks-key-alias ${{ secrets.KEY_ALIAS }} --ks-pass env:KEYSTORE_PASSWORD --key-pass env:KEY_PASSWORD --out app/build/outputs/apk/release/app-release-signed.apk app/build/outputs/apk/release/app-release-unsigned.apk
          ${ANDROID_HOME}/build-tools/33.0.0/apksigner verify app/build/outputs/apk/release/app-release-signed.apk
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release-signed.apk

env:
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
