name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Pode ajustar para a distribuição JDK de sua preferência
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Sign and Verify APK
        run: |
          echo ${{ secrets.KEYSTORE_BASE64 }} | base64 --decode > keystore/santander.jks
          ${ANDROID_HOME}/build-tools/33.0.0/apksigner sign --ks keystore/santander.jks --ks-key-alias ${{ secrets.KEY_ALIAS }} --ks-pass env:KEYSTORE_PASSWORD --key-pass env:KEY_PASSWORD --out app/release/app-release-signed.apk app/release/app-release-signed.apk
          ${ANDROID_HOME}/build-tools/33.0.0/apksigner verify app/release/app-release-signed.apk


      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: app/release/app-release-signed.apk

env:
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
